### ISSUE TITLE
Scénario à envisager pour déploiement module téléchargement

### ISSUE THREAD

**Issue by IGNF-Xavier** [IGNF/geonetwork-ui#3]
A étudier :

- scénario 1 : développement sur un fork du datahub dev de @cdebarros 
- scénario 2 : développement sur datahub dev de @cdebarros mais avec possibilité de désactiver ce module
- scénario 3 : développement sur autre datahub dev-IGN ou externe (Camptocamp)

Préférence MOA : scénario 2 pour cohérence. 
A noter que ne connaissant pas quand le catalogue serait déployé, il pourrait l'être avec ou sans le module de téléchargement, le module de téléchargement arrivant un peu plus tard.

**Comment by IGNF-Xavier** [comment]
@mmohadIGN je ne peux pas t'assigner le ticket

**Comment by tomalary** [comment]
@mmohadIGN tu m'as dit qu'après discussion avec @cdebarros un scénario à deux branches était proposé/envisagé ? Tu confirmes ?

**Comment by mmohadIGN** [comment]
Oui, je confirme @tomalary. On centralise le dépôt, mais on code en parallèle. Avec des merges régulier du travail de Christopher et nous pour être capable de déployer quand notre solution sera prête.
