### ISSUE TITLE
[BUG] Erreur dans la balise téléchargement de la métadonnée parcellaire express

### ISSUE THREAD

**Issue by mmohadIGN** [IGNF/geonetwork-ui#44]
L'URL dans la Métadonnée du parcellaire express est mauvaise. Elle empêche l'accès au module de téléchargement.

L'URL inscrite dans la métadonnée est : https://data.geopf.fr/telechargement/resource/PARCELLAIREEXPRESS au lieu de https://data.geopf.fr/telechargement/resource/PARCELLAIRE-EXPRESS

La correction est à faire dans la balise <gmd:URL> rattaché à la balise <gmx:MimeFileType type="">WWW:DOWNLOAD-1.0-http--download</gmx:MimeFileType>

**Comment by IGNF-Xavier** [comment]
@fdubreil @SBarroca

**Comment by IGNF-Xavier** [comment]
Testé, cela fonctionne mais je n'ai pas les droits pour clore ce tickets.
Merci @fdubreil et @mmohadIGN

**Comment by mmohadIGN** [comment]
Je clos merci
